### ISSUE TITLE
Couldn't Get it to Run

### ISSUE THREAD

**Issue by johe7140** [CaptBrunch/Muk_CSCI2270_FinalProject#1]
I tried running the program and it wouldn't build successfully. It seems the issue is in main and its a scope issue with brackets opening or closing statements incorrectly. I also noticed a syntax error in main. The line
int index2 = line2, find(",");
I believe should be 
int index2 = line2.find(",");

**Comment by CaptBrunch** [comment]
Yeah I'll have it fixed by today sorry about that I might have put an
outdated main filee

**Comment by CaptBrunch** [comment]
Sorry I wasn't able to fix it by Thursday, I was really busy and was able
to finish it up until now but it should run.
