### ISSUE TITLE
Wouldn't Run

### ISSUE THREAD

**Issue by mljunker** [CaptBrunch/Muk_CSCI2270_FinalProject#2]
Couldn't compile from terminal and so couldn't run. I got these issues when trying to compile.
Creating a CodeBlocks project with your code didn't work either.
Let me know if this is my own unfamiliarity with using terminal commands. 
The first issue seems to be stoi in main. You seem to be including the correct libraries so I don't know why it won't compile.

> user@cu-cs-vm:~/Downloads/Muk_CSCI2270_FinalProject-master$ g++ main.cpp
> main.cpp: In function ‘int main(int, char**)’:
> main.cpp:46:42: error: ‘stoi’ was not declared in this scope
>                      distValue = stoi(temp);
>                                           ^
> main.cpp:59:16: error: no matching function for call to ‘std::basic_ifstream<char>::open()’
>      file2.open()("landMarks.txt")
>                 ^
> main.cpp:59:16: note: candidate is:
> In file included from main.cpp:2:0:
> /usr/include/c++/4.8/fstream:538:7: note: void std::basic_ifstream<_CharT, _Traits>::open(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
>        open(const char_ __s, ios_base::openmode __mode = ios_base::in)
>        ^
> /usr/include/c++/4.8/fstream:538:7: note:   candidate expects 2 arguments, 0 provided
> main.cpp:60:5: error: expected ‘;’ before ‘List’
>      List l;
>      ^
> main.cpp:63:23: error: no matching function for call to ‘std::basic_ifstream<char>::open()’
>          if(file2.open())
>                        ^
> main.cpp:63:23: note: candidate is:
> In file included from main.cpp:2:0:
> /usr/include/c++/4.8/fstream:538:7: note: void std::basic_ifstream<_CharT, _Traits>::open(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
>        open(const char_ __s, ios_base::openmode __mode = ios_base::in)
>        ^
> /usr/include/c++/4.8/fstream:538:7: note:   candidate expects 2 arguments, 0 provided
> main.cpp:72:29: error: ‘line’ was not declared in this scope
>          while(getline(file2,line))
>                              ^
> main.cpp:75:13: error: ‘city’ was not declared in this scope
>              city = line.substr(0,index);
>              ^
> main.cpp:76:13: error: ‘line2’ was not declared in this scope
>              line2 = line.substr(index+1, line.length());
>              ^
> main.cpp:78:40: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
>              int index2 = line2,find(",");
>                                         ^
> main.cpp:79:13: error: ‘landM’ was not declared in this scope
>              landM = line2.substr(0,index2);
>              ^
> main.cpp:80:13: error: ‘line3’ was not declared in this scope
>              line3 = line2.substr(index2+1,line2.length());
>              ^
> main.cpp:83:13: error: ‘cost’ was not declared in this scope
>              cost = stoi(line3.substr(0,index3));
>              ^
> main.cpp:83:47: error: ‘stoi’ was not declared in this scope
>              cost = stoi(line3.substr(0,index3));
>                                                ^
> main.cpp:85:13: error: ‘l’ was not declared in this scope
>              l.createLL(city,landM,cost);
>              ^
> main.cpp:102:33: error: ‘stoi’ was not declared in this scope
>          int choiceI = stoi(input);
>                                  ^
> main.cpp:132:17: error: ‘l’ was not declared in this scope
>                  l.Budget(startingCity,b);
>                  ^
> main.cpp:155:21: error: ‘l’ was not declared in this scope
>                      l.poi(startingCity);
>                      ^
> main.cpp:178:17: error: ‘l’ was not declared in this scope
>                  l.popularLandmarks(startingCity);
>                  ^
> main.cpp:180:14: error: jump to case label [-fpermissive]
>          case 6:
>               ^
> main.cpp:165:22: error:   crosses initialization of ‘bool found’
>                  bool found = false;
>                       ^
> main.cpp:161:24: error:   crosses initialization of ‘std::string startingCity’
>                  string startingCity;
>                         ^
> main.cpp:187:9: error: jump to case label [-fpermissive]
>          default:
>          ^
> main.cpp:165:22: error:   crosses initialization of ‘bool found’
>                  bool found = false;
>                       ^
> main.cpp:161:24: error:   crosses initialization of ‘std::string startingCity’
>                  string startingCity;
>                         ^
> main.cpp:193:5: error: expected ‘}’ at end of input
>      }
>      ^
> main.cpp:193:5: error: expected ‘}’ at end of input
> user@cu-cs-vm:~/Downloads/Muk_CSCI2270_FinalProject-master$ g++ main.cpp -o
> g++: error: missing filename after ‘-o’
> user@cu-cs-vm:~/Downloads/Muk_CSCI2270_FinalProject-master$ g++ main.cpp -o mainmain.cpp: In function ‘int main(int, char**)’:
> main.cpp:46:42: error: ‘stoi’ was not declared in this scope
>                      distValue = stoi(temp);
>                                           ^
> main.cpp:59:16: error: no matching function for call to ‘std::basic_ifstream<char>::open()’
>      file2.open()("landMarks.txt")
>                 ^
> main.cpp:59:16: note: candidate is:
> In file included from main.cpp:2:0:
> /usr/include/c++/4.8/fstream:538:7: note: void std::basic_ifstream<_CharT, _Traits>::open(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
>        open(const char_ __s, ios_base::openmode __mode = ios_base::in)
>        ^
> /usr/include/c++/4.8/fstream:538:7: note:   candidate expects 2 arguments, 0 provided
> main.cpp:60:5: error: expected ‘;’ before ‘List’
>      List l;
>      ^
> main.cpp:63:23: error: no matching function for call to ‘std::basic_ifstream<char>::open()’
>          if(file2.open())
>                        ^
> main.cpp:63:23: note: candidate is:
> In file included from main.cpp:2:0:
> /usr/include/c++/4.8/fstream:538:7: note: void std::basic_ifstream<_CharT, _Traits>::open(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
>        open(const char_ __s, ios_base::openmode __mode = ios_base::in)
>        ^
> /usr/include/c++/4.8/fstream:538:7: note:   candidate expects 2 arguments, 0 provided
> main.cpp:72:29: error: ‘line’ was not declared in this scope
>          while(getline(file2,line))
>                              ^
> main.cpp:75:13: error: ‘city’ was not declared in this scope
>              city = line.substr(0,index);
>              ^
> main.cpp:76:13: error: ‘line2’ was not declared in this scope
>              line2 = line.substr(index+1, line.length());
>              ^
> main.cpp:78:40: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
>              int index2 = line2,find(",");
>                                         ^
> main.cpp:79:13: error: ‘landM’ was not declared in this scope
>              landM = line2.substr(0,index2);
>              ^
> main.cpp:80:13: error: ‘line3’ was not declared in this scope
>              line3 = line2.substr(index2+1,line2.length());
>              ^
> main.cpp:83:13: error: ‘cost’ was not declared in this scope
>              cost = stoi(line3.substr(0,index3));
>              ^
> main.cpp:83:47: error: ‘stoi’ was not declared in this scope
>              cost = stoi(line3.substr(0,index3));
>                                                ^
> main.cpp:85:13: error: ‘l’ was not declared in this scope
>              l.createLL(city,landM,cost);
>              ^
> main.cpp:102:33: error: ‘stoi’ was not declared in this scope
>          int choiceI = stoi(input);
>                                  ^
> main.cpp:132:17: error: ‘l’ was not declared in this scope
>                  l.Budget(startingCity,b);
>                  ^
> main.cpp:155:21: error: ‘l’ was not declared in this scope
>                      l.poi(startingCity);
>                      ^
> main.cpp:178:17: error: ‘l’ was not declared in this scope
>                  l.popularLandmarks(startingCity);
>                  ^
> main.cpp:180:14: error: jump to case label [-fpermissive]
>          case 6:
>               ^
> main.cpp:165:22: error:   crosses initialization of ‘bool found’
>                  bool found = false;
>                       ^
> main.cpp:161:24: error:   crosses initialization of ‘std::string startingCity’
>                  string startingCity;
>                         ^
> main.cpp:187:9: error: jump to case label [-fpermissive]
>          default:
>          ^
> main.cpp:165:22: error:   crosses initialization of ‘bool found’
>                  bool found = false;
>                       ^
> main.cpp:161:24: error:   crosses initialization of ‘std::string startingCity’
>                  string startingCity;
>                         ^
> main.cpp:193:5: error: expected ‘}’ at end of input
>      }
>      ^
> main.cpp:193:5: error: expected ‘}’ at end of input
> user@cu-cs-vm:~/Downloads/Muk_CSCI2270_FinalProject-master$

**Comment by CaptBrunch** [comment]
I fixed everything and it should be good to go sorry for the inconvenience
